-- Create tables for SÉLAH

-- PROFILES (extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- CATEGORIES
create table public.categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_es text not null,
  slug text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PRODUCTS
create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories,
  slug text unique not null,
  name_en text not null,
  name_es text not null,
  description_en text,
  description_es text,
  price_eur decimal(10,2) not null,
  price_usd decimal(10,2) not null,
  images text[], -- Array of image URLs
  stock integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDERS
create table public.orders (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users,
  email text not null, -- For guest checkout
  stripe_session_id text unique,
  amount_total decimal(10,2) not null,
  currency text not null,
  status text default 'pending', -- pending, paid, shipped, cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDER ITEMS
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders not null,
  product_id bigint references public.products not null,
  quantity integer default 1,
  price_at_purchase decimal(10,2) not null
);

-- QR ACCESS (The special feature)
create table public.qr_access (
  id uuid default uuid_generate_v4() primary key,
  order_id uuid references public.orders not null,
  qr_token text unique not null,
  is_active boolean default true,
  accessed_at timestamp with time zone, -- Last access
  expires_at timestamp with time zone, -- Optional expiry
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.qr_access enable row level security;

-- Policies (Simple examples)
create policy "Public profiles are viewable by everyone." on public.profiles for select using ( true );
create policy "Users can insert their own profile." on public.profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on public.profiles for update using ( auth.uid() = id );

-- Products are public
alter table public.products enable row level security;
create policy "Public products" on public.products for select using ( true );

-- Categories are public
alter table public.categories enable row level security;
create policy "Public categories" on public.categories for select using ( true );
